# Build the Electron installer with a direct Cloudflare backend URL.

param(
    [Parameter(Mandatory=$true)]
    [ValidatePattern('^https?://')]
    [string]$BackendUrl,

    [Parameter(Mandatory=$false)]
    [ValidatePattern('^(wss?|https?)://')]
    [string]$WebSocketUrl = "",

    [string]$Environment = "production",

    [switch]$PublishUpdates,

    [string]$UpdatesPath = "",

    [string]$UpdatesSshHost = "",

    [string]$UpdatesRemotePath = "",

    [switch]$SkipInstall
)

$ErrorActionPreference = "Stop"

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$projectRoot = Split-Path -Parent $scriptDir
$appDir = Join-Path $projectRoot "app"
$tempEnvFile = $null
$previousEnv = @{
    APS_APP_CONFIG_ENV_FILE = $env:APS_APP_CONFIG_ENV_FILE
    VITE_API_URL = $env:VITE_API_URL
    VITE_BACKEND_ENVIRONMENT = $env:VITE_BACKEND_ENVIRONMENT
    VITE_WS_URL = $env:VITE_WS_URL
}
$pushedLocation = $false

try {
    if (-not (Test-Path $appDir)) {
        throw "app directory not found: $appDir"
    }

    $tempEnvFile = New-TemporaryFile
    $envLines = @(
        "# Generated by scripts/build-app-release.ps1",
        "VITE_API_URL=$BackendUrl",
        "VITE_BACKEND_ENVIRONMENT=$Environment"
    )

    if (-not [string]::IsNullOrWhiteSpace($WebSocketUrl)) {
        $envLines += "VITE_WS_URL=$WebSocketUrl"
    }

    Set-Content -LiteralPath $tempEnvFile.FullName -Encoding utf8 -Value $envLines
    $env:APS_APP_CONFIG_ENV_FILE = $tempEnvFile.FullName
    $env:VITE_API_URL = $BackendUrl
    $env:VITE_BACKEND_ENVIRONMENT = $Environment
    if (-not [string]::IsNullOrWhiteSpace($WebSocketUrl)) {
        $env:VITE_WS_URL = $WebSocketUrl
    } else {
        Remove-Item Env:VITE_WS_URL -ErrorAction SilentlyContinue
    }

    Push-Location $appDir
    $pushedLocation = $true

    if (-not $SkipInstall) {
        npm install
        if ($LASTEXITCODE -ne 0) { throw "npm install failed" }
    }

    npm run electron:build
    if ($LASTEXITCODE -ne 0) { throw "electron build failed" }

    Write-Host ""
    Write-Host "Build artifacts:" -ForegroundColor Cyan
    Get-ChildItem -Path (Join-Path $appDir "dist") -File |
        Where-Object { $_.Name -match '(\.exe|latest\.yml|\.blockmap)$' } |
        Select-Object Name, Length, LastWriteTime

    if ($PublishUpdates) {
        $publishScript = Join-Path $scriptDir "publish-app-update.ps1"
        $publishArgs = @{
            DistPath = (Join-Path $appDir "dist")
        }

        if (-not [string]::IsNullOrWhiteSpace($UpdatesPath)) {
            $publishArgs.UpdatesPath = $UpdatesPath
        }
        if (-not [string]::IsNullOrWhiteSpace($UpdatesSshHost)) {
            $publishArgs.UpdatesSshHost = $UpdatesSshHost
        }
        if (-not [string]::IsNullOrWhiteSpace($UpdatesRemotePath)) {
            $publishArgs.UpdatesRemotePath = $UpdatesRemotePath
        }

        & $publishScript @publishArgs
        if ($LASTEXITCODE -ne 0) { throw "update artifact publish failed" }
    }
}
finally {
    if ($pushedLocation) {
        Pop-Location
    }

    foreach ($key in $previousEnv.Keys) {
        if ($null -eq $previousEnv[$key]) {
            Remove-Item "Env:$key" -ErrorAction SilentlyContinue
        } else {
            Set-Item "Env:$key" $previousEnv[$key]
        }
    }

    if ($tempEnvFile -and (Test-Path -LiteralPath $tempEnvFile.FullName)) {
        Remove-Item -LiteralPath $tempEnvFile.FullName -Force
    }
}
